name: Update property for sonar-update-center

on:
  push:
    branches:
      - actions-test

jobs:
  sonar-update-center:
    runs-on: ubuntu-latest
    steps:
      - uses: KengoTODA/sonar-update-center-action@main
        with:
          prop-file: findbugs.properties
          description: Use SpotBugs 4.2.0, sb-contrib 7.4.7, and findsecbugs 1.11.0
          minimal-supported-sq-version: 7.9
          latest-supported-sq-version: LATEST
          changelog-url: https://github.com/spotbugs/sonar-findbugs/releases/tag/4.0.3
          download-url: https://repo.maven.apache.org/maven2/com/github/spotbugs/sonar-findbugs-plugin/4.0.3/sonar-findbugs-plugin-4.0.3.jar
          public-version: 4.0.3
          sonar-cloud-url: https://sonarcloud.io/dashboard?branch=4.0.3&id=com.github.spotbugs%3Asonar-findbugs-plugin
          github-token: ${{ secrets.PAT_TO_FORK }}
          discourse-username: KengoTODA
          discourse-api-key: ${{ secrets.DISCOURSE_API_KEY }}
